name: Test Package

on: [push, pull_request]

jobs:
  test:
    name: Test Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          lfs: true
      
      - name: Run Tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: TestProject~
          githubToken: ${{ secrets.GITHUB_TOKEN }}